version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: byeolnight-mysql-local
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: byeolnight
      MYSQL_USER: byeolnight
      MYSQL_PASSWORD: byeolnight123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_local:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: byeolnight-redis-local
    ports:
      - "6379:6379"
    volumes:
      - redis_data_local:/data
    restart: unless-stopped

volumes:
  mysql_data_local:
  redis_data_local: