# 로컬 개발 환경
# 사용법: docker-compose -f docker-compose.local.yml up -d

services:
  config-server:
    build:
      context: ./config-server
    ports:
      - "8888:8888"
    environment:
      - ENCRYPT_KEY=byeolnight-config-encryption-key-2024
      - SPRING_SECURITY_USER_NAME=config-admin
      - SPRING_SECURITY_USER_PASSWORD=config-secret-2024
      - SPRING_PROFILES_ACTIVE=local
      - CONFIG_GIT_URI=file:///opt/byeolnight/config-repo
    volumes:
      - ./config-repo:/opt/byeolnight/config-repo:ro
    restart: unless-stopped
    networks:
      - byeolnight-network

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: byeolnight9703!@
      MYSQL_DATABASE: byeolnight
      TZ: Asia/Seoul
    command: >
      --innodb-buffer-pool-size=256M
      --innodb-log-file-size=64M
      --max-connections=20
      --innodb-flush-log-at-trx-commit=2
      --default-time-zone='+09:00'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_local:/var/lib/mysql
    restart: unless-stopped
    networks:
      - byeolnight-network

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data_local:/data
    command: redis-server --requirepass byeolnight_redis_2025!@ --maxmemory 128mb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - byeolnight-network

volumes:
  mysql_data_local:
  redis_data_local:

networks:
  byeolnight-network:
    driver: bridge