spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

send:
  from: ${MAIL_FROM}

coolsms:
  api-key: ${COOLSMS_API_KEY}
  api-secret: ${COOLSMS_API_SECRET}
  sender-number: ${COOLSMS_SENDER}

server:
  port: 8080

# sendgrid:
#   api-key: YOUR_SENDGRID_API_KEY
#   from-email: no-reply@byeolnight.com
