server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: file:///app/config-repo/configs
        git:
          uri: file:///tmp/config-repo
          clone-on-start: false
        encrypt:
          enabled: false
  security:
    user:
      name: ${SPRING_SECURITY_USER_NAME:config-admin}
      password: ${SPRING_SECURITY_USER_PASSWORD:config-secret-2024}
  profiles:
    active: native

management:
  endpoints:
    web:
      exposure:
        include: health,info