name: Branch Protection Check

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check source branch
        run: |
          if [[ "${{ github.base_ref }}" == "main" && "${{ github.head_ref }}" != "develop" ]]; then
            echo "❌ main 브랜치는 develop에서만 머지 가능합니다"
            exit 1
          fi
          echo "✅ 브랜치 규칙 준수"

  quality-gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run tests
        run: ./gradlew test

      - name: Build
        run: ./gradlew build -x test

      - name: Quality Gate
        if: success()
        run: echo "✅ 품질 테스트 통과"

      - name: Quality Gate Failed
        if: failure()
        run: |
          echo "❌ 품질 테스트 실패"
          echo "모든 테스트가 통과해야 머지 가능합니다"
          exit 1
